# Generated by Django 4.1.3 on 2023-02-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_book_maincategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mainCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_by_main_category', to='base.category'),
        ),
    ]
