# Generated by Django 4.1.3 on 2023-02-27 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_book_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
